### PR TITLE
fix(typegen): generate in managed mode when server-entry.tsx exists

### LINKED ISSUE #1747: Typegen breaks when server-entry.ts exists
Since middleware was removed from `defineConfig` in waku.config.ts, the only remaining way to provide middleware as i see is by creating a server-entry.ts with `middlewareFns`. However, doing so breaks typegen (pages.gen.ts) because of the `entriesFilePossibilities` condition in fs-router-typegen.ts — it simply checks for the existence of the server-entry file and returns void if it exists.

As a result, there is currently no way to provide middleware without breaking the typegen (pages.gen.ts).

### PR DESCRIPTION
**Pull request by tylersayshi**
fixes #1747

### CODE REVIEW

File: packages/waku/src/lib/vite-plugins/fs-router-typegen.ts [hunk 1]
```diff
@@ -73,18 +73,52 @@ export const fsRouterTypegenPlugin = (opts: { srcDir: string }): Plugin => {
...
+            readFileSync(existingServerEntry, 'utf8'),
+            {
+              syntax: 'typescript',
+              tsx: true,
+            },
+          );
+
+          const usesCreatePages = file.body.some((node) => {
+            if (node.type === 'ImportDeclaration') {
+              if (node.source.value !== 'waku') {
```
Comment (dai-shi) [inline packages/waku/src/lib/vite-plugins/fs-router-typegen.ts]: It's technically possible and valid to do `import { fsRouter } from 'waku/router/server'`.

**Review by dai-shi — APPROVED** [review]
Looks good otherwise.

What's your opinion?

File: packages/waku/src/lib/vite-plugins/fs-router-typegen.ts (hunk 1 above)
Comment (tylersayshi) [reply packages/waku/src/lib/vite-plugins/fs-router-typegen.ts]: That should still generate types I think because it's still using filesystem routing. 

With this logic that would still run the generation because we only check for createPages being used to disable generation.

Comment (dai-shi) [reply packages/waku/src/lib/vite-plugins/fs-router-typegen.ts]: Oh, this is `usesCreatePages`. Got it.

Then, my concern is that we shouldn't run generation for this case: https://github.com/wakujs/waku/blob/fe8fb224abbaba0fa962782a25690264945e1114/examples/31_minimal/src/server-entry.tsx

And, also `import { createPages } from 'waku/router/server'` should be detected.

**Review by dai-shi — CHANGES_REQUESTED** [review]
https://github.com/wakujs/waku/pull/1748#discussion_r2496665067

GitHub doesn't have a capability to "unapprove".

File: packages/waku/src/lib/vite-plugins/fs-router-typegen.ts (hunk 1 above)
Comment (tylersayshi) [reply packages/waku/src/lib/vite-plugins/fs-router-typegen.ts]: should this check be `!node.source.value.startsWith('waku')` then you think?

Comment (dai-shi) [reply packages/waku/src/lib/vite-plugins/fs-router-typegen.ts]: @tylersayshi 
I think we should have `usesFsRouter` instead of `!usesCreatePages`.
And check `import { fsRouter } from 'waku'` or `import { fsRouter } from 'waku/router/server'`.

Comment (tylersayshi) [reply packages/waku/src/lib/vite-plugins/fs-router-typegen.ts]: if it uses fsRouter wouldn't we still want to run the typegen?

Comment (dai-shi) [reply packages/waku/src/lib/vite-plugins/fs-router-typegen.ts]: We want to run the typegen, if fsRouter is used. Otherwise, we don't. No need to check the existence of `createPages`.

Comment (tylersayshi) [reply packages/waku/src/lib/vite-plugins/fs-router-typegen.ts]: thanks! updated to match that logic

**Review by dai-shi — APPROVED** [review]
