### PR TITLE
fix(create-pages): sanitize slugs used for create pages paths

### LINKED ISSUE #1782: `staticPaths` breaks with slugs with `.` (dots) in them.
Assume code that looks like this:

```tsx
export async function getConfig() {
  const pages = blogSource.getPages();
  const slugs = pages.map((page) => [page.data.slug]);

  console.log('slugs', slugs); // [ ["v1.0.0"], ["v1.1.0"] ]

  return {
    render: 'static' as const,
    staticPaths: slugs,
  } as const;
}
```

This doesn't work in practice because when `waku` generates the routes ahead of time, it strips out the dots from the slugs causing the links to not work in practice.

That said, `.` is not a special character in actual URLs. When a slug contains `.` and the same component is used in "dynamic" mode, everything works correctly.

### PR DESCRIPTION
**Pull request by tylersayshi**
This change makes it so we:

- no longer strip "." from page routes
- correctly detect the difference between files and folders without relying on the `.` as only being an extension for static output to not cause a regression for #803 

I tested this locally to be sure the static output and `waku start` both serve the new routes correctly. I also did my best to add testing, but am unsure what to do for static output tests for routes with dots: https://github.com/wakujs/waku/pull/1787#issuecomment-3539711657

fixes #1782

### CODE REVIEW

**Comment by tylersayshi** [comment]
static tests with our http server: [serve](https://www.npmjs.com/package/serve) will not work with testing in playwright the "." pages because it returns the folder view instead of the rendered index.html

image

The correct files exist, so other static file servers can be expected to act correctly with this change, but I'm not sure how we can actually test it without fixing serve or changing the http server used for testing

**Comment by dai-shi** [comment]
> static tests with our http server: [serve](https://www.npmjs.com/package/serve) will not work with testing in playwright the "." pages because it returns the folder view instead of the rendered index.html

I tried `npx serve` locally, but it shows `index.html`.

**Comment by tylersayshi** [comment]
> I tried `npx serve` locally, but it shows `index.html`.

@dai-shi can you be a bit more detailed with how you did this? I've been trying to get that working for a long while now.

also, if you're able to get it working with the e2e tests, feel free to update this branch.

File: packages/waku/src/lib/vite-rsc/handler.ts [hunk 1]
```diff
@@ -128,7 +133,7 @@ const toProcessBuild =
       generateFile: async (pathname: string, body: ReadableStream | string) => {
         const filePath = joinPath(
           DIST_PUBLIC,
-          extname(pathname)
+          isFile(pathname)
```
Comment (hi-ogawa) [inline packages/waku/src/lib/vite-rsc/handler.ts]: I think whether `pathname` should be saved as `(pathname)/index.html` should be decided by the caller of `generateFile` (i.e. router) since the caller knows whether it's rendering rsc/html or not. I.e whether `isFile` or not should be router's responsibility.

So maybe we need to change the signature of `generateFile` to be something like `generateFile(pathname, contentType, body)` or `generateFile(pathname, exact, body)`

Comment (dai-shi) [inline packages/waku/src/lib/vite-rsc/handler.ts]: This will be problematic. It will now make `/foo/bar.png/index.html`.
I think `generateFile` should receive `filename` instead.

**Comment by dai-shi** [comment]
> > I tried `npx serve` locally, but it shows `index.html`.
> 
> @dai-shi can you be a bit more detailed with how you did this? I've been trying to get that working for a long while now.
> 
> also, if you're able to get it working with the e2e tests, feel free to update this branch.

I don't see any problems now.
@tylersayshi you reverted to `serve` in dca1721808f55e6d9af716738c6cdcbf119c7f58.

File: packages/waku/src/lib/vite-rsc/handler.ts (hunk 1 above)
Comment (dai-shi) [reply packages/waku/src/lib/vite-rsc/handler.ts]: https://github.com/wakujs/waku/pull/1787#discussion_r2532597592 I'll work on it.

Comment (dai-shi) [reply packages/waku/src/lib/vite-rsc/handler.ts]: #1792 oh you opened it.

**Comment by tylersayshi** [comment]
>I don't see any problems now.
@tylersayshi you reverted to serve in https://github.com/wakujs/waku/commit/dca1721808f55e6d9af716738c6cdcbf119c7f58.

There are no problems now because we have no e2e tests for fixtures that have routes like /v1.0.0 - when a test for that is added is when the issue with serve can be observed

File: packages/waku/src/lib/vite-rsc/handler.ts (hunk 1 above)
Comment (tylersayshi) [reply packages/waku/src/lib/vite-rsc/handler.ts]: thank you both for the help on that

**Comment by dai-shi** [comment]
> can you be a bit more detailed with how you did this? I've been trying to get that working for a long while now.

@tylersayshi This is what I did:
```bash
mkdir -p public/foo
echo '<h1>FOO</h1>' > public/foo/index.html
npx serve public
```

Ahhh

```bash
mkdir -p public/v1.0.0
echo '<h1>v100</h1>' > public/v1.0.0/index.html
npx serve public
```

Okay, now I see it.

```bash
mkdir -p public/v1.0.0/foo
echo '<h1>v100 - foo</h1>' > public/v1.0.0/foo/index.html
npx serve public
```

This works. Could you create a test with this workaround?
