### PR TITLE
fix: batch flight data

### LINKED ISSUE #1861: RSC flight data should be consolidated
It currently pollutes the DOM with separate `<script>` tags even on statically prerendered routes (chunks only make sense for streaming).

Image

### PR DESCRIPTION
**Pull request by dai-shi**
close #1861

### CODE REVIEW

File: packages/waku/src/lib/utils/stream.ts [hunk 1]
```diff
@@ -34,3 +34,49 @@ export const base64ToStream = (base64: string): ReadableStream => {
...
+  const buffer: Uint8Array[] = [];
+  let timer: ReturnType<typeof setTimeout> | undefined;
+
+  const flushBuffer = (
+    controller: TransformStreamDefaultController<Uint8Array>,
+  ): void => {
+    clearTimeout(timer);
+    timer = undefined;
+    if (buffer.length) {
+      controller.enqueue(concatUint8Array(buffer));
```
Comment (hi-ogawa) [inline packages/waku/src/lib/utils/stream.ts]: Batching makes sense to me, but doing `controller.enqueue` inside `setTimeout` can crash server with unhandled error with aborted stream etc. I think it's safe to silence any error by `try { ... } catch { }` similar to https://github.com/devongovett/rsc-html-stream/pull/10

Comment (dai-shi) [reply packages/waku/src/lib/utils/stream.ts]: Thanks for the catch!
