### PR TITLE
fix(router): empty router issue and added mapping

### LINKED ISSUE #1978: Static API route with wildcard causes file-system conflicts
when there's an empty path in `staticPaths`, the error can be reproduced.

```ts
// _api/llms.mdx/docs/[...slugs].ts
import { ApiContext } from 'waku/router';
import { unstable_notFound } from 'waku/router/server';

export async function GET(_: Request, { params }: ApiContext<'/llms.mdx/docs/[...slugs]'>) {
  const slugs = params.slugs;
  console.log(slugs);
  return new Response('hello world', {
    headers: {
      'Content-Type': 'text/markdown',
    },
  });
}

export async function getConfig() {
  return {
    render: 'static' as const,
    staticPaths: [[], ['test']],
  } as const;
}
```

Image

### PR DESCRIPTION
**Pull request by tylersayshi**
fixes #1978

### CODE REVIEW

File: packages/waku/src/router/define-router.tsx [hunk 1]
```diff
@@ -665,11 +675,21 @@ export function unstable_defineRouter(fns: {
       if (!pathname) {
         continue;
       }
+      // If this pathname is also a directory prefix for another static API
+      // route, emit as pathname/index to avoid file-system conflicts.
```
Comment (dai-shi) [inline packages/waku/src/router/define-router.tsx]: I'm not sure about this. What use cases is this trying to cover?

Comment (tylersayshi) [reply packages/waku/src/router/define-router.tsx]: The one from #1978. It supports the empty staticPath as a / on /[...wildcard]

Comment (dai-shi) [reply packages/waku/src/router/define-router.tsx]: Hmm, but adding `/index` here seems wrong. Any other solution?

Comment (tylersayshi) [reply packages/waku/src/router/define-router.tsx]: this should be better now - just warning based on the issue conversation
